// Custom Arsenal Preset
GRLIB_arsenal_weapons = [
	"BWA3_G27",
	"BWA3_G27_Tan",
	"BWA3_G27_AG",
	"BWA3_G27_Tan_AG",
	"BWA3_G28_Standard",
	"BWA3_G28_Assault",
	"BWA3_G36",
	"BWA3_G36_LMG",
	"BWA3_G36_AG",
	"BWA3_G36K",
	"BWA3_G36K_AG",
	"BWA3_G38",
	"BWA3_G38_Tan",
	"BWA3_G38_AG",
	"BWA3_G38_AG_Tan",
	"BWA3_G38C",
	"BWA3_G38C_Tan",
	"BWA3_G38K",
	"BWA3_G38K_Tan",
	"BWA3_G38K_AG",
	"BWA3_G38K_AG_Tan",
	"BWA3_G82",
	"BWA3_MG3",
	"BWA3_MG4",
	"BWA3_MG5",
	"BWA3_MG5_Tan",
	"BWA3_Fliegerfaust",
	"BWA3_CarlGustaf",
	"BWA3_Pzf3",
	"BWA3_RGW90",
	"BWA3_MP7",
	"BWA3_P2A1",
	"BWA3_P8",
	"CUP_arifle_G36K",
	"CUP_arifle_G36A_camo",
	"CUP_arifle_G36A",
	"CUP_arifle_G36C",
	"CUP_arifle_G36C_camo",
	"CUP_arifle_G36K_camo",
	"CUP_arifle_MG36A",
	"CUP_arifle_MG36A_camo",
	"CUP_hgun_Glock17",
	"CUP_hgun_Glock17_blk",
	"CUP_hgun_Glock17_tan"
	
];

GRLIB_arsenal_magazines = [

];

GRLIB_arsenal_items = [
	"BWA3_optic_RSAS",
	"BWA3_optic_Aimpoint",
	"BWA3_optic_EOTech",
	"BWA3_optic_EOTech_tan",
	"BWA3_optic_EOTech_Mag_Off",
	"BWA3_optic_EOTech_Mag_On",
	"BWA3_optic_EOTech_tan_Mag_Off",
	"BWA3_optic_EOTech_tan_Mag_On",
	"BWA3_optic_NSV80",
	"BWA3_optic_ZO4x30",
	"BWA3_optic_ZO4x30_NSV",
	"BWA3_optic_ZO4x30_IRV",
	"BWA3_optic_ZO4x30_Single",
	"BWA3_optic_ZO4x30_Single_NSV",
	"BWA3_optic_ZO4x30_Single_IRV",
	"BWA3_optic_Shortdot",
	"BWA3_optic_20x50",
	"BWA3_optic_20x50_NSV",
	"BWA3_optic_24x72",
	"BWA3_optic_24x72_NSV"
	"BWA3_Uniform_Crew_Fleck",
	"BWA3_Uniform_Helipilot",
	"BWA3_Uniform_Crew_Tropen",
	"BWA3_Uniform_Ghilie_Fleck",
	"BWA3_Uniform_Ghilie_Tropen",
	"BWA3_Uniform_Fleck",
	"BWA3_Uniform2_Fleck",
	"",
	
	"BWA3_acc_LLM01_irlaser",
	"BWA3_acc_LLM01_flash",
	"BWA3_acc_LLM01_laser",
	"BWA3_acc_LLM01_underbarrel_irlaser",
	"BWA3_acc_LLM01_underbarrel_flash",
	"BWA3_acc_LLM01_underbarrel_laser",
	"BWA3_acc_VarioRay_irlaser",
	"BWA3_acc_VarioRay_flash",
	"BWA3_acc_VarioRay_laser",
	"BWA3_Vest_Flecktarn",
	"BWA3_Vest_Autorifleman_Fleck",
	"BWA3_Vest_Grenadier_Fleck",
	"BWA3_Vest_Marksman_Fleck",
	"BWA3_Vest_Medic_Fleck",
	"BWA3_Vest_Rifleman1_Fleck",
	"BWA3_Vest_Leader_Fleck",
	"BWA3_Vest_Autorifleman_Tropen",
	"BWA3_Vest_Grenadier_Tropen",
	"BWA3_Vest_Marksman_Tropen",
	"BWA3_Vest_Medic_Tropen",
	"BWA3_Vest_Rifleman1_Tropen",
	"BWA3_Vest_Leader_Tropen",
	"BWA3_Vest_JPC_Radioman_Fleck",
	"BWA3_Vest_JPC_Rifleman_Fleck",
	"BWA3_Vest_JPC_Leader_Fleck",
	"BWA3_Vest_JPC_Radioman_Tropen",
	"BWA3_Vest_JPC_Rifleman_Tropen",
	"BWA3_Vest_JPC_Leader_Tropen",
];

GRLIB_arsenal_backpacks = [


];